from datetime import datetime
import os


def generate_report(report_data):

    if not os.path.exists("reports"):
        os.makedirs("reports")

    timestamp = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")

    filename = f"reports/diagnostic_report_{timestamp}.txt"

    with open(filename, "w") as report:

        # Report Header

        report.write("=" * 50 + "\n")
        report.write("             SECURE IT SUPPORT TOOLKIT\n")
        report.write("                  SYSTEM REPORT\n")
        report.write("=" * 50 + "\n\n")

        report.write(
            f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}\n\n"
        )


        # Report Sections

        for section, information in report_data.items():

            report.write("\n")
            report.write("=" * 50 + "\n")
            report.write(f"{section.upper()}\n")
            report.write("=" * 50 + "\n\n")


            # Dictionary

            if isinstance(information, dict):

                for key, value in information.items():

                    # Dictionary containing another dictionary

                    if isinstance(value, dict):

                        report.write(f"{key}:\n")
                        report.write("-" * len(key) + "\n")

                        for item, details in value.items():

                            report.write(f"{item}: {details}\n")

                        report.write("\n")


                    # Dictionary containing a list

                    elif isinstance(value, list):

                        report.write(f"{key}:\n")
                        report.write("-" * len(key) + "\n\n")

                        for item in value:

                            if isinstance(item, dict):

                                for item_key, item_value in item.items():

                                    report.write(
                                        f"{item_key}: {item_value}\n"
                                    )

                                report.write("\n")
                                report.write("-" * 50 + "\n\n")

                            else:

                                report.write(f"{item}\n")


                    # Normal dictionary value

                    else:

                        report.write(f"{key}: {value}\n")


            # List

            elif isinstance(information, list):

                for item in information:

                    if isinstance(item, dict):

                        for key, value in item.items():

                            report.write(f"{key}: {value}\n")

                        report.write("\n")
                        report.write("-" * 50 + "\n\n")

                    else:

                        report.write(f"{item}\n")


            # Normal value

            else:

                report.write(f"{information}\n")


        # Report Footer

        report.write("\n")
        report.write("=" * 50 + "\n")
        report.write("      GENERATED BY SECURE IT SUPPORT TOOLKIT\n")
        report.write("=" * 50 + "\n")